name: 🐞 Bug Report
description: File a bug report if something is not working as expected.
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        To ensure you're on the right track, confirm that submitting 
        a bug report is the best way to handle your issue.

        * For technical questions, post a question on
        [StackOverflow](http://stackoverflow.com/) with the `firebase` tag.

        * For general questions on CLI usage, please take a look at the guide 
        first: https://firebase.google.com/docs/cli/

        * For backend, console, and other non-CLI issues, reach out to
        [Firebase Support](https://firebase.google.com/support/) for help.

        If your issue doesn't fit the description above and is related to the 
        code in this repository not working correctly, please fill out this 
        form and submit this bug report. Thank you!

        If you know how to solve the issue, please create a Pull Request, and 
        we'd be happy to review it!
        
  - type: input
    attributes:
      label: Firebase Tools Version
      description: What version of Firebase Tools has this issue? You can find the latest versions in https://github.com/firebase/firebase-tools/releases
      placeholder: "14.4.0"
    validations:
      required: true
  - type: input
    attributes:
      label: Platform
      description: What Platform are you using? i.e. macOS, Windows, Ubuntu, etc.
      placeholder: "macOS Sequoia 15.4.1"
    validations:
      required: true
  - type: dropdown
    id: is-using-vs-code-extension
    attributes:
      label: Are you using the Firebase Data Connect VS code extension?
      options:
        - Yes
        - No
  - type: textarea
    attributes:
      label: Firebase Data Connect VS Code extension version
      description: Firebase Data Connect VS Code extension version?
      placeholder: "1.4.0"
    validations:
      required: true
    rules:
      - type: required
        message: Please describe the bug.
        if:
          is-using-vs-code-extension:
            - Yes
  - type: textarea
    attributes:
      label: Test Case
      description: |
        Provide a minimal, complete, and verifiable example (http://stackoverflow.com/help/mcve) 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      description: |
        Provide the steps needed to reproduce the issue with the above test case.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        What is the _expected_ behavior? 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        What is the _actual_ behavior? 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output. To enable debug
        logging, add the `--debug` flag to your command. i.e. `firebase emulators:start --debug`.
        You can also paste the contents of your `firebase-debug.log` file
      placeholder: |
        Paste your logs here. Please redact any personally identifiable
        information. This will be automatically formatted into code, so no
        need for backticks.
      render: shell
    validations:
      required: false
