name: 🐞 Bug Report
description: File a bug report if something is not working as expected.
labels: ["type: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the Firebase Community!

       Have a feature request?
        ========================
        Great, we love hearing how we can improve our products! However, do not use this template to submit a feature request. Please submit your feature requests to: https://firebase.google.com/support/contact/bugs-features/

        Have a usage question?
        =======================
        We get lots of those and we love helping you, but GitHub is not the best place for them and they will be closed. Please take a look at the [Firebase CLI documentation](https://firebase.google.com/docs/cli/) first: 
        If the official documentation doesn't help, try asking through our official [support channel](https://firebase.google.com/support/).
        You can also post a question on[StackOverflow](http://stackoverflow.com/) with the `firebase` tag.
        
        Have a backend, console, and other non-CLI issues?
        =======================
        This repository might not be the best place to address this issue, please reach out to [Firebase Support](https://firebase.google.com/support/) for help.

        Think you found a bug?
        =======================
        Yeah, we're definitely not perfect! Please use this template to provide information about the issue. If you know how to solve the issue, please create a Pull Request, and we'd be happy to review it!
        
  - type: input
    attributes:
      label: Firebase Tools Version
      description: What version of Firebase Tools has this issue? You can find the latest versions in https://github.com/firebase/firebase-tools/releases
      placeholder: "14.4.0"
    validations:
      required: true
  - type: input
    attributes:
      label: Platform
      description: What Platform are you using? i.e. macOS, Windows, Ubuntu, etc.
      placeholder: "macOS Sequoia 15.4.1"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other tool versions
      description: If you're using other relevant tools like Node.js, Firebase Data Connect VS Code extension, etc. please list them.
      placeholder: |
        Node.js: v20.19.0
        npm: v10.8.0
        Firebase Data Connect VS Code extension: v1.4.0
    validations:
      required: false
  - type: textarea
    attributes:
      label: Test Case
      description: |
        Provide a minimal, complete, and verifiable example (http://stackoverflow.com/help/mcve) 
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      description: |
        Provide the steps needed to reproduce the issue with the above test case.
      placeholder: |
        1. Run the command '...'
        2. Click on '....'
        2. See error '...'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        What is the _expected_ behavior? 
      placeholder: |
        The Firebase CLI should have...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual behavior
      description: |
        What is the _actual_ behavior? 
      placeholder: |
        The Firebase CLI threw an error message '...'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: |
        Please copy and paste any relevant log output. To enable debug
        logging, add the `--debug` flag to your command. i.e. `firebase emulators:start --debug`.
        You can also paste the contents of your `firebase-debug.log` file
      placeholder: |
        Paste your logs here. Please redact any personally identifiable
        information. This will be automatically formatted into code, so no
        need for backticks.
      render: shell
    validations:
      required: false
