name: Feature/Bug Report with Conditional Fields
description: Report a new feature request or a bug.
labels: ["bug", "enhancement"]
assignees:
  - octocat # Replace with your GitHub username

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute! Please fill in the necessary information below.

  - type: checkboxes
    id: issue-type
    attributes:
      label: What type of issue is this?
      options:
        - label: Bug Report
          description: Report a problem with existing functionality
        - label: Feature Request
          description: Suggest a new feature or enhancement

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
    # Show this field only if "Bug Report" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please describe the bug.
        if:
          issue-type:
            - Bug Report

  - type: textarea
    id: bug-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    # Show this field only if "Bug Report" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please provide steps to reproduce the bug.
        if:
          issue-type:
            - Bug Report

  - type: textarea
    id: bug-expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    # Show this field only if "Bug Report" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please describe the expected behavior.
        if:
          issue-type:
            - Bug Report

  - type: textarea
    id: bug-actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happens.
    # Show this field only if "Bug Report" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please describe the actual behavior.
        if:
          issue-type:
            - Bug Report

  - type: string
    id: feature-title
    attributes:
      label: Feature Title
      description: A clear and concise title for the feature request.
    # Show this field only if "Feature Request" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please provide a title for your feature request.
        if:
          issue-type:
            - Feature Request

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
    # Show this field only if "Feature Request" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please describe the feature.
        if:
          issue-type:
            - Feature Request

  - type: textarea
    id: feature-alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you've considered.
    # Show this field only if "Feature Request" is checked
    rules:
      - type: required
        name: atLeastOneRequired
        message: Please describe the alternatives you considered.
        if:
          issue-type:
            - Feature Request

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
